name: suppchild_ver_1
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  charts_flutter: ^0.8.1
  dropdown_formfield: ^0.1.3
  bmnav: ^0.3.4
  image_picker: ^0.6.7+14
  carousel_slider: ^2.3.1
  group_radio_button: ^1.0.1
  custom_radio_grouped_button: ^1.0.6+1
  http: ^0.12.2
  file_picker: 
  dio: ^3.0.9
  path: ^1.6.4
  url_launcher:
  geolocator: ^5.3.1
  splashscreen:
  intl: ^0.16.1
  # firebase
  cloud_firestore: ^0.14.4
  shared_preferences: ^0.5.8
  firebase_core : ^0.5.0
  flutter_session: ^0.1.1
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.0

  fl_chart: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Medium.ttf
        - asset: assets/font/Rubik-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/font/Rubik-SemiBold.ttf
          weight: 800
    - family: MyFlutterApp
      fonts:
        - asset: assets/font/MyFlutterApp.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
